# Generated by Django 5.1.1 on 2024-09-26 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('radius', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='blocks.block')),
                ('to_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='blocks.block')),
            ],
        ),
    ]
